import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { client, exploreProfiles } from '../api'
// import styles from '../styles/Home.module.css'
import { useConnectWallet } from '@web3-onboard/react'

export default function Home() {
  const [profiles, setProfiles] = useState<Array<{[property: string]: any}>>([])
  const [{ wallet, connecting }, connect, disconnect] = useConnectWallet()

  useEffect(() => {
    async function fetchProfiles() {
      const response = await client.query({ query: exploreProfiles })
      console.log(response.data.exploreProfiles.items)
      setProfiles(response.data.exploreProfiles.items)
      }
      fetchProfiles()
  }, [])

  return (
    <div className='container pt-10 text-center'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-4xl m-2'>Lucky Lens</h1>
      <button className='bg-green-700 text-white rounded-xl p-2 mt-2' disabled={connecting} onClick={() => (wallet ? disconnect(wallet) : connect())}>
        {connecting ? 'connecting' : wallet ? 'disconnect' : 'connect'}
      </button>
    </div>
  )
}
